name: flutter_ume_kit_ui
description: UI Kits for flutter_ume.
version: 1.1.1
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    git: 
      url: git@github.com:pumpkincrypto/flutter_ume.git
  touch_indicator: ^2.0.0

  # for Cyclop
  image: ^4.0.15
  quiver: ^3.2.1
  basics: ">=0.6.0 <0.11.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

flutter:
